import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  FIXTURE_CONNECTION_PROOF_MANIFEST,
  verifyFixtureConnectionProofManifest,
  type FixtureConnectionProofEvidence,
  type FixtureConnectionProofScreenshot,
  type FixtureConnectionProofVerificationResult
} from './fixture-proof.js';
import { DEFAULT_SEPOLIA_CHAIN_ID } from './network.js';
import { maskEthereumAddress } from './profile-bootstrap.js';
import {
  connectWallet,
  type WalletControlLogger,
  type WalletDappDriver,
  type WalletGuardrailConfig,
  type WalletPromptDriver
} from './wallet-control.js';
import type { MetaMaskNetworkDriver } from './network.js';

export interface FixtureConnectionScreenshotCaptureInput {
  path: string;
  evidence: FixtureConnectionProofEvidence;
}

export interface RunFixtureConnectionProofOptions {
  artifactDir: string;
  dapp: WalletDappDriver;
  prompt: WalletPromptDriver;
  network: MetaMaskNetworkDriver;
  origin: string;
  expectedAccount: string;
  expectedChainId?: string | number;
  allowedOrigins?: readonly string[];
  captureScreenshot(input: FixtureConnectionScreenshotCaptureInput): Promise<void>;
  logger?: WalletControlLogger;
  notes?: readonly string[];
}

interface FixtureConnectionProofManifest {
  artifactType: 'fixture-dapp-wallet-connection-proof';
  target: 'fixture-dapp';
  status: 'connected';
  evidence: FixtureConnectionProofEvidence;
  screenshots: FixtureConnectionProofScreenshot[];
  notes: string[];
}

export async function runFixtureConnectionProof(
  options: RunFixtureConnectionProofOptions
): Promise<FixtureConnectionProofVerificationResult> {
  const artifactDir = options.artifactDir;
  mkdirSync(artifactDir, { recursive: true, mode: 0o700 });

  const connection = await connectWallet({
    dapp: options.dapp,
    prompt: options.prompt,
    network: options.network,
    expectedAccount: options.expectedAccount,
    expectedChainId: options.expectedChainId ?? DEFAULT_SEPOLIA_CHAIN_ID,
    origin: options.origin,
    guardrails: createFixtureGuardrails(options),
    logger: options.logger
  });

  const evidence: FixtureConnectionProofEvidence = {
    connectionState: 'connected',
    maskedAccount: maskEthereumAddress(connection.activeAccount),
    chainId: connection.chainId,
    origin: sanitizeProofOrigin(options.origin)
  };

  const screenshotFile = 'fixture-connected.png';
  const screenshotPath = join(artifactDir, screenshotFile);
  await options.captureScreenshot({ path: screenshotPath, evidence });
  const screenshot = createScreenshotManifestEntry(artifactDir, screenshotFile);

  const manifest: FixtureConnectionProofManifest = {
    artifactType: 'fixture-dapp-wallet-connection-proof',
    target: 'fixture-dapp',
    status: 'connected',
    evidence,
    screenshots: [screenshot],
    notes: [
      'Generated by local fixture connection proof harness after wallet-control verified account and chain.',
      'Artifact is local-only under .wallet-artifacts and must be inspected before sharing.',
      ...(options.notes ?? [])
    ]
  };

  writeFileSync(join(artifactDir, FIXTURE_CONNECTION_PROOF_MANIFEST), `${JSON.stringify(manifest, null, 2)}\n`, { mode: 0o600 });
  return verifyFixtureConnectionProofManifest(artifactDir);
}

function createFixtureGuardrails(options: RunFixtureConnectionProofOptions): WalletGuardrailConfig {
  return {
    allowedOrigins: options.allowedOrigins ?? [sanitizeProofOrigin(options.origin)],
    maxTransactionValueWei: 0n
  };
}

function createScreenshotManifestEntry(artifactDir: string, file: 'fixture-connected.png'): FixtureConnectionProofScreenshot {
  const screenshotPath = join(artifactDir, file);
  const bytes = readFileSync(screenshotPath);
  return {
    label: 'fixture-connected',
    file,
    sizeBytes: statSync(screenshotPath).size,
    sha256: createHash('sha256').update(bytes).digest('hex')
  };
}

function sanitizeProofOrigin(origin: string): string {
  const parsed = new URL(origin);
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error('Fixture proof origin must be an http(s) URL.');
  }
  return `${parsed.origin}${parsed.pathname === '/' ? '' : parsed.pathname}`;
}
