import { createHash, randomUUID } from 'node:crypto';
import { mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  FIXTURE_CONNECTION_PROOF_MANIFEST,
  verifyFixtureConnectionProofManifest,
  type FixtureConnectionProofEvidence,
  type FixtureConnectionProofScreenshot,
  type FixtureConnectionProofVerificationResult
} from './fixture-proof.js';
import { DEFAULT_SEPOLIA_CHAIN_ID } from './network.js';
import { maskEthereumAddress } from './profile-bootstrap.js';
import {
  connectWallet,
  type WalletControlLogger,
  type WalletDappDriver,
  type WalletGuardrailConfig,
  type WalletPromptDriver
} from './wallet-control.js';
import type { MetaMaskNetworkDriver } from './network.js';

export interface FixtureConnectionScreenshotCaptureInput {
  path: string;
  evidence: FixtureConnectionProofEvidence;
}

export interface RunFixtureConnectionProofOptions {
  artifactDir: string;
  dapp: WalletDappDriver;
  prompt: WalletPromptDriver;
  network: MetaMaskNetworkDriver;
  origin: string;
  expectedAccount: string;
  expectedChainId?: string | number;
  allowedOrigins?: readonly string[];
  captureScreenshot(input: FixtureConnectionScreenshotCaptureInput): Promise<void>;
  logger?: WalletControlLogger;
  notes?: readonly string[];
}

interface FixtureConnectionProofManifest {
  schemaVersion: 1;
  createdAt: string;
  runId: string;
  provenance: {
    packageName: '@broccolo1d/wallet-browser';
    packageVersion: string;
    framework: 'wallet-browser';
    tool: 'runFixtureConnectionProof';
    runtime: {
      node: string;
      platform: string;
      arch: string;
    };
  };
  artifactType: 'fixture-dapp-wallet-connection-proof';
  target: 'fixture-dapp';
  status: 'connected';
  evidence: FixtureConnectionProofEvidence;
  screenshots: FixtureConnectionProofScreenshot[];
  notes: string[];
}

const WALLET_BROWSER_PACKAGE_VERSION = '0.2.8';

function runtimeMetadata(): FixtureConnectionProofManifest['provenance']['runtime'] {
  return { node: process.version, platform: process.platform, arch: process.arch };
}

export async function runFixtureConnectionProof(
  options: RunFixtureConnectionProofOptions
): Promise<FixtureConnectionProofVerificationResult> {
  const artifactDir = options.artifactDir;
  mkdirSync(artifactDir, { recursive: true, mode: 0o700 });

  const connection = await connectWallet({
    dapp: options.dapp,
    prompt: options.prompt,
    network: options.network,
    expectedAccount: options.expectedAccount,
    expectedChainId: options.expectedChainId ?? DEFAULT_SEPOLIA_CHAIN_ID,
    origin: options.origin,
    guardrails: createFixtureGuardrails(options),
    logger: options.logger
  });

  const evidence: FixtureConnectionProofEvidence = {
    connectionState: 'connected',
    maskedAccount: maskEthereumAddress(connection.activeAccount),
    chainId: connection.chainId,
    origin: sanitizeProofOrigin(options.origin)
  };

  const screenshotFile = 'fixture-connected.png';
  const screenshotPath = join(artifactDir, screenshotFile);
  await options.captureScreenshot({ path: screenshotPath, evidence });
  const screenshot = createScreenshotManifestEntry(artifactDir, screenshotFile);

  const manifest: FixtureConnectionProofManifest = {
    schemaVersion: 1,
    createdAt: new Date().toISOString(),
    runId: `fixture-connection-proof-${randomUUID()}`,
    provenance: {
      packageName: '@broccolo1d/wallet-browser',
      packageVersion: WALLET_BROWSER_PACKAGE_VERSION,
      framework: 'wallet-browser',
      tool: 'runFixtureConnectionProof',
      runtime: runtimeMetadata()
    },
    artifactType: 'fixture-dapp-wallet-connection-proof',
    target: 'fixture-dapp',
    status: 'connected',
    evidence,
    screenshots: [screenshot],
    notes: [
      'Generated by local fixture connection proof harness after wallet-control verified account and chain.',
      'Artifact is local-only under .wallet-artifacts and must be inspected before sharing.',
      ...(options.notes ?? []).map(redactProofNote)
    ]
  };

  writeFileSync(join(artifactDir, FIXTURE_CONNECTION_PROOF_MANIFEST), `${JSON.stringify(manifest, null, 2)}\n`, { mode: 0o600 });
  return verifyFixtureConnectionProofManifest(artifactDir);
}

function createFixtureGuardrails(options: RunFixtureConnectionProofOptions): WalletGuardrailConfig {
  return {
    allowedOrigins: options.allowedOrigins ?? [sanitizeProofOrigin(options.origin)],
    maxTransactionValueWei: 0n
  };
}

function createScreenshotManifestEntry(artifactDir: string, file: 'fixture-connected.png'): FixtureConnectionProofScreenshot {
  const screenshotPath = join(artifactDir, file);
  const bytes = readFileSync(screenshotPath);
  return {
    label: 'fixture-connected',
    file,
    sizeBytes: statSync(screenshotPath).size,
    sha256: createHash('sha256').update(bytes).digest('hex')
  };
}

function sanitizeProofOrigin(origin: string): string {
  const parsed = new URL(origin);
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error('Fixture proof origin must be an http(s) URL.');
  }
  return `${parsed.origin}${parsed.pathname === '/' ? '' : parsed.pathname}`;
}

function redactProofNote(note: string): string {
  return note
    .replace(/\bnpm_[A-Za-z0-9_-]{20,}\b/g, '[redacted:npm-token]')
    .replace(/https?:\/\/[^\s"'`]+:[^\s"'`@]+@[^\s"'`]+/gi, '[redacted:rpc-url]')
    .replace(/https?:\/\/[^\s"'`]*\/(?:[^\s"'`]*[A-Za-z0-9_-]{20,}[^\s"'`]*)/gi, '[redacted:rpc-url]')
    .replace(/https?:\/\/[^\s"'`]+[?&](?:api[_-]?key|token|key|auth|access[_-]?token)=[^\s"'`&]+/gi, '[redacted:rpc-url]')
    .replace(/\b(?:private[_-]?key|seed(?:[ _-]?phrase)?|mnemonic|password|passphrase|secret|token|rpc(?:[_-]?url)?)\b\s*(?::|=|is|was)?\s+[^\n\r]*/gi, (match) => redactLabeledSecret(match))
    .replace(/\b(?:0x)?[0-9a-fA-F]{64}\b/g, '[redacted:secret]')
    .replace(/0x[0-9a-fA-F]{40}/g, maskEthereumAddress)
    .replace(/[A-Za-z]:\\(?:[^\\\s]+\\)*([^\\\s]+)/g, '[path]/$1')
    .replace(/\/(?:[^/\s]+\/)+([^/\s]+)/g, '[path]/$1');
}

function redactLabeledSecret(value: string): string {
  const label = value.match(/private[_-]?key|seed(?:[ _-]?phrase)?|mnemonic|password|passphrase|secret|token|rpc(?:[_-]?url)?/i)?.[0] ?? 'secret';
  return `[redacted:${label.toLowerCase().replace(/[ _]/g, '-')}]`;
}
